<html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'>
<meta name='applicable-device' content='pc'><meta name='keywords' content='电脑,电脑讲解,电脑技术,编程,电脑故障维修Java异常类及处理' />
<script src='../../highlight/highlight.pack.js'></script>
<link rel='stylesheet' type='text/css' href='../../highlight/styles/monokai.css'/>

<link rel='stylesheet' href='../../fenxiang/dist/css/share.min.css'>
<script src='../../fenxiang/src/js/social-share.js'></script>
<script src='../../fenxiang/src/js/qrcode.js'></script>

</head><body><script>hljs.initHighlightingOnLoad();</script><script>
var system ={};  
var p = navigator.platform;       
system.win = p.indexOf('Win') == 0;  
system.mac = p.indexOf('Mac') == 0;  
system.x11 = (p == 'X11') || (p.indexOf('Linux') == 0);     
if(system.win||system.mac||system.xll){
document.write("<link href='../css/3.css' rel='stylesheet' type='text/css'>");}else{ document.write("<link href='../css/3wap.css' rel='stylesheet' type='text/css'>");}</script><script src='../../js/3.js'></script><div class='div2'><div class='heading_nav'><ul><div><li><a href='../../index.html'>首页</a></li>
</div><div onclick='hidden1()' >分享</div>
</ul></div></div>
<div id='heading_nav2'> 
<li class='row' >
<div class='social-share' data-mode='prepend'><a href='javascript:' class='social-share-icon icon-heart'></a></div></li></div><script charset='utf-8' src='../../3/js/hengfu.js'></script><script charset='utf-8' src='../../3/js/hengfu2.js'></script><hr><div class='div1'><div class='biaoti'><center>Java异常类及处理</center></div><div class='banquan'>原文出处:本文由博客园博主青鸟i提供。<br/>
原文连接:https://www.cnblogs.com/Dm920/p/11681802.html</div><br>
    <h2><span style="color: #ff0000;">异常概述</span>：运行时发生的不正常情况</h2>
<p><span style="font-size: 14px;">在java中用类的形式对不正常的情况进行了描述和封装对象。</span></p>
<p><span style="font-size: 14px;">描述不正常的类，称之为<span data-wiz-span="data-wiz-span"><span style="color: #ff0000;">异常类</span>。</span></span></p>
<p><span style="font-size: 14px;">异常就是java通过面向对象的思想将问题封装成了对象，用异常类对其进行描述。</span></p>
<p><span style="font-size: 14px; color: #008000;">不同的问题用不同的类进行具体的描述，比如角标越界，空指针等。</span></p>
<h3>异常体系两大类：</h3>
<p>无论是<span data-wiz-span="data-wiz-span">error，还是Exception，问题发生就应该可以抛出，让调用者知道并处理，</span><span>该体系的特点就在于<span data-wiz-span="data-wiz-span"><span style="color: #0000ff;">Throwable</span>及其所有子类都具备可抛性。</span></span></p>
<p><strong><span style="color: #0000ff;" data-wiz-span="data-wiz-span">Throwable</span>：</strong></p>
<src class="cnblogs_code">
<pre><code><span style="color: #000000;">① 一般不可处理的。<span style="color: #0000ff;">Error</span>

特点：是由JVM抛出的严重性问题；这种问题一般不针对处理，直接修改程序。

② 可处理的。<span style="color: #0000ff;">Exception</span>
<span style="text-decoration: underline;">
可抛性</span>：被<span style="color: #0000ff;">throws</span> 和 <span style="color: #0000ff;">throw</span> 关键字所操作的类和对象都具备可抛性

<span style="text-decoration: underline;">该体系的特点</span>：<span style="color: #008000;">子类的后缀名都是用其父类名作为后缀名，阅读性很强。</span></span></code></pre>

<h3>异常分类：</h3>
<src class="cnblogs_code">
<pre><code><span style="color: #000000;">检测性异常：即除RuntimeException及其子类以外的异常。这类异常在编译时就进行检测，不处理不能通过；

非检测性异常：即运运行时异常RuntimeException及其子类。这类异常不处理变异也可以通过，如果有抛出 直接抛到控制台让调用者进行修正；</span></code></pre>

<h3>自定义异常：</h3>
<p>要么继承&nbsp;<span data-wiz-span="data-wiz-span">Exception&nbsp;要么继承&nbsp;<span data-wiz-span="data-wiz-span">RuntimeException</span></span></p>
<p><span style="font-size: 14px;">如果抛出一个在Java中没有定义过的异常，这时就需要自定义创建一个异常类。</span></p>
<p><span style="font-size: 14px;"><span style="color: #ff0000;">注</span>：<span style="text-decoration: underline;"><span style="color: #ff0000; text-decoration: underline;">自定义一个异常类，必须要继承一个异常体系才可以被抛出，被throw throws所操作</span></span></span></p>
<h3>异常抛出注意事项：</h3>
<p><span data-wiz-span="data-wiz-span">子类覆盖父类只能抛出父类的异常或者子类或者子集</span></p>
<src class="cnblogs_code">
<pre><code><span>① 子类在覆盖父类方法时，父类方法如果抛出了异常，那么子类的方法只能抛出父类异常或者该父类异常的子类；

② 如果父类抛出多个异常，那么子类只能抛出父类异常的子集</span></code></pre>

<p><span><span data-wiz-span="data-wiz-span"><span style="color: #ff0000;">注意</span>：<span style="text-decoration: underline; color: #ff0000;"><span data-wiz-span="data-wiz-span">如果父类的方法没有抛出，那么子类覆盖式也决不能抛出，只能try</span></span></span></span></p>
<h2><span style="color: #ff0000;">异常处理</span>：<span data-wiz-span="data-wiz-span">throw，throws和</span><span data-wiz-span="data-wiz-span">try...catch;finally;</span></h2>
<p><span style="color: #008000;">用类封装描述异常（称为异常类），不同的问题不同的类，当程序中遇到可能会发生异常的时候抛出异常类或进行捕获异常处理。</span></p>
<h3><span data-wiz-span="data-wiz-span">异常抛出</span></h3>
<p><strong><span data-wiz-span="data-wiz-span">throw&nbsp;<span data-wiz-span="data-wiz-span"><span data-wiz-span="data-wiz-span">和&nbsp;</span></span></span><span data-wiz-span="data-wiz-span">throws&nbsp;</span></strong><span data-wiz-span="data-wiz-span"><strong><span data-wiz-span="data-wiz-span">的区别</span></strong>：</span></p>
<p><span style="font-size: 14px;">① throw：使用在函数内，throw抛出的是异常对象；<span style="color: #008000;">throw new 异常类 ( )</span></span></p>
<p><span style="font-size: 14px;">② throws：使用在函数上，throws抛出的是异常类，可抛出多个，用逗号隔开( , )；<span style="color: #008000;">throws 类名，...，...，&nbsp;</span></span></p>
<p><span style="color: #0000ff;" data-wiz-span="data-wiz-span"><strong>PS</strong>:<span style="text-decoration: underline;">当 throw new RuntimeException的时候，不用throws</span></span></p>
<p><strong><span style="font-size: 14px;">throw：</span></strong></p>
<p><span>抛出一个异常，一般是在函数代码块的内部，当程序出现某种逻辑错误时由程序员主动抛出某种特定类型的异常</span></p>
<src class="cnblogs_code">
<pre><code><span style="color: #0000ff;">public</span> <span style="color: #0000ff;">void</span><span style="color: #000000;"> getOffer(String s) {
    </span><span style="color: #0000ff;">if</span>(s.equals("abc"<span style="color: #000000;">)) {
        </span><span style="color: #0000ff;">throw</span> <span style="color: #0000ff;">new</span><span style="color: #000000;"> NumberFormatException();
    }
    </span><span style="color: #0000ff;">if</span>(s.equals(""<span style="color: #000000;">)) {
        </span><span style="color: #0000ff;">throw</span> <span style="color: #0000ff;">new</span> Exception("输入参 S 不能为空"<span style="color: #000000;">);
    } </span><span style="color: #0000ff;">else</span><span style="color: #000000;"> {
        System.out.println(s);
    }
}</span></code></pre>

<p><strong>throws：</strong></p>
<p>可能抛出异常的声明&nbsp; (用在声明方法时，表示该方法可能要抛出异常)</p>
<p>当某个方法可能会抛出某种异常时用于throws 声明可能抛出的异常，然后交给上层调用它的方法程序处理</p>
<src class="cnblogs_code">
<pre><code><span style="color: #0000ff;">public</span> <span style="color: #0000ff;">class</span><span style="color: #000000;"> testThrows(){
    </span><span style="color: #0000ff;">public</span> <span style="color: #0000ff;">static</span> <span style="color: #0000ff;">void</span> function() <span style="color: #0000ff;">throws</span><span style="color: #000000;"> NumberFormatException{ 
        String s </span>= "abc"<span style="color: #000000;">;
        System.out.println(Double.parseDouble(s));
    }
    </span><span style="color: #0000ff;">public</span> <span style="color: #0000ff;">static</span> <span style="color: #0000ff;">void</span><span style="color: #000000;"> main(String[] args) {
        </span><span style="color: #0000ff;">try</span><span style="color: #000000;"> {
            function();
        } </span><span style="color: #0000ff;">catch</span><span style="color: #000000;"> (NumberFormatException e) {
            System.err.println(</span>"非数据类型不能强制类型转换。"<span style="color: #000000;">);
    }
}</span></code></pre>

<h3>异常捕捉</h3>
<p><strong>捕获异常</strong>：<span data-wiz-span="data-wiz-span">try...catch<span class="Apple-converted-space">&nbsp;</span></span>关键字捕获异常<span data-wiz-span="data-wiz-span"><span class="Apple-converted-space">&nbsp;tay...catch放在异常可能会发生的地方</span></span></p>
<src class="cnblogs_code">
<pre><code><span style="color: #0000ff;">try</span><span style="color: #000000;">
{
    </span><span style="color: #008000;">//</span><span style="color: #008000;">需要被检测异常的代码（保护代码块）</span>
}<span style="color: #0000ff;">catch</span>(异常类 引用名)<span style="color: #008000;">//</span><span style="color: #008000;">该类用于接收发生的异常对象</span>
<span style="color: #000000;">{
    </span><span style="color: #008000;">//</span><span style="color: #008000;">处理异常的代码（异常类）</span>
}<span style="color: #0000ff;">catch</span><span style="color: #000000;">(异常类 引用名)
{   </span><span style="color: #008000;">//</span><span style="color: #008000;">可多重捕获，可在try语句后面添加任意数量的catch块.</span>
    <span style="color: #008000;">/*</span><span style="color: #008000;"> 如果保护代码中发生异常，异常抛给第一个catch块,异常相匹配的话，则在这里被捕获。如果不匹配，
       就会传给第二个catch块，如此直到异常被捕获或通过所有catch块为止 </span><span style="color: #008000;">*/</span>
    <span style="color: #008000;">//</span><span style="color: #008000;">一个try块下的多个catch异常类型有父子关系，应该将子类异常放在前面，父类异常放在后面，这样保证每个catch块都有存在的意义</span>
<span style="color: #000000;">}
</span><span style="color: #0000ff;">finally</span> <span style="color: #008000;">//</span><span style="color: #008000;">通常用于关闭（释放）资源</span>
<span style="color: #000000;">{ 
    </span><span style="color: #008000;">//</span><span style="color: #008000;">finally代码块里面的动作必定会执行，无论有没有发现捕获异常，都一定会执行的代码
    </span><span style="color: #008000;">//</span><span style="color: #008000;">一个try至少要有一个catch块，否则， 至少要有1个finally块。但是finally不是用来处理异常的，finally不会捕获异常。             
     </span><span style="color: #008000;">//</span><span style="color: #008000;">finally主要做一些清理工作，如流的关闭，数据库连接的关闭等。</span>
}</code></pre>

<p><strong><span data-wiz-span="data-wiz-span">try catch<span class="Apple-converted-space">&nbsp;<span data-wiz-span="data-wiz-span">finally<span class="Apple-converted-space">&nbsp;代码块组合特点</span></span></span></span></strong>：</p>
<src class="cnblogs_code">
<pre><code>① <span style="color: #0000ff;">try</span> <span style="color: #0000ff;">catch</span> <span style="color: #0000ff;">finally</span><span style="color: #000000;">

② </span><span style="color: #0000ff;">try</span> <span style="color: #0000ff;">catch</span><span style="color: #000000;">（多个）当没必要资源需要释放时，可以不用定义finally

③ </span><span style="color: #0000ff;">try</span> <span style="color: #0000ff;">finally</span>  异常无法直接catch处理，但是资源需要关闭</code></pre>

<p class="_mce_tagged_br"><strong>捕获处理原则</strong>：</p>
<p class="_mce_tagged_br">在写程序时，对可能会出现异常的部分通常要用try{...}catch{...}去捕捉它并对它进行处理；</p>
<p class="_mce_tagged_br">用try{...}catch{...}捕捉了异常之后一定要对在catch{...}中对其进行处理，那怕是最简单的一句输出语句，或栈输入e.printStackTrace();</p>
<p class="_mce_tagged_br"><span style="color: #008000;" data-wiz-span="data-wiz-span">try对应多个catch时，如果有父类的catch语句块，一定要放在下面。<br class="_mce_tagged_br" /></span></p>
<p><span style="color: #008000;">如果是捕捉IO输入输出流中的异常，一定要在try{...}catch{...}后加finally{...}把输入输出流关闭；</span></p>
<p><span style="text-decoration: underline;">如果在函数体内用throw抛出了某种异常，最好要在函数名中加throws抛异常声明，然后交给调用它的上层函数进行处理</span></p>
<h3>异常处理原则：</h3>
<src class="cnblogs_code">
<pre><code><span style="color: #000000;">① 函数内部如果抛出需要检测的异常，那么函数上必须要声明。否则必须要在函数内使用try...catch捕捉，否则编译失败；<br /><span style="color: #ff0000;">　 ( RuntimeException以外的异常需要throws声明 ）</span>
② 如果调用到了声明异常的函数，要么ctry catch要么throws，否则编译失败。

③ 功能内容可以解决是用catch；解决不了用throws告诉调用者，由调用者解决。

④ 一个功能如果抛出了多个异常，调用时必须有多个catch进行针对性处理。内部有几个需要检测的异常，就抛几个异常，抛出几个就catch几个；</span></code></pre>

<p>&nbsp;</p>
<h3>&nbsp;</h3>
<p>&nbsp;</p>

</div><hr><script charset='utf-8' src='../../js/sming.js'></script></body></html>